### ISSUE TITLE
$ not redering 

### ISSUE THREAD

**Issue by ajbraus** [jreese/markdown-pp#67]
Love markdown-pp, but having trouble with the $ character

```Electric standing desks range from $200-$2000. ```

Rendering: 200-2000. A survey found standing desk advocates would be happy with the  ...
Traceback (most recent call last):
  File "/usr/local/bin/markdown-pp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/main.py", line 112, in main
    MarkdownPP.MarkdownPP(input=mdpp, output=md, modules=modules)
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/MarkdownPP.py", line 28, in __init__
    pp.process()
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/Processor.py", line 49, in process
    transforms = module.transform(self.data)
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/Modules/LaTeXRender.py", line 77, in transform
    self.render(tex) +
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/Modules/LaTeXRender.py", line 100, in render
    formula = formula.replace("$", "")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 163: ordinal not in range(128)

Tried with `\$` and I get the same error 

Rendering: 200-\2000. A survey found standing desk advocates would be happy with the  ...
Traceback (most recent call last):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 163: ordinal not in range(128)

**Comment by hayekian** [comment]
THis has been mentioned before.. fixed with:

"append -e latexrender to the command you use to call MarkdownPP."   fixed it for me
--
