### ISSUE TITLE
Special characters in heading break TOC generation

### ISSUE THREAD

**Issue by moehrenzahn** [jreese/markdown-pp#72]
When generating a table of contents with a heading that contains a special unicode character such as `®` fails:

## Test markdown:

```
# Test document

!TOC

## Test ® Test

The following is a test.
```

## markdown-pp error output:
```
❯ markdown-pp test_pp.md -o test.md                   
Traceback (most recent call last):
  File "/usr/local/bin/markdown-pp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/main.py", line 112, in main
    MarkdownPP.MarkdownPP(input=mdpp, output=md, modules=modules)
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/MarkdownPP.py", line 28, in __init__
    pp.process()
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/Processor.py", line 49, in process
    transforms = module.transform(self.data)
  File "/usr/local/lib/python2.7/site-packages/MarkdownPP/Modules/TableOfContents.py", line 119, in transform
    TableOfContents.clean_title(title)).lower()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
```

Expected behaviour:

- Unicode characters in headings should be allowed

**Comment by jreese** [comment]
This is a problem with Python 2.7. if you install/use this with Python 3, it will work just fine.
